### ISSUE TITLE
PolyKinded MFunctor

### ISSUE THREAD

**Issue by jkarni** [Gabriel439/Haskell-MMorph-Library#29]
Currently `MFunctor` has kind `(* -> *) -> * -> *`. Is there any reason not to adopt the more general `(* -> *) -> k -> *`? The general use-case is making things like [`vinyl` records](https://hackage.haskell.org/package/vinyl-0.5.2/docs/Data-Vinyl-Core.html) instances (with `hoist = rmap`).

(By the way, I've always really liked this library, and this seems like a good occasion to say so!)

**Comment by Gabriel439** [comment]
Alright.  I'm usually reluctant to make type classes poly-kinded but I think there is a sufficiently compelling case here because:

* There is only one kind parameter, so it won't deteriorate the generated haddocks that much
* It has an immediate practical application in `vinyl` ...
* ... which would still obey the `hoist` laws (i.e. `hoist id = id`, `hoist (f . g) = hoist f . hoist g`)

Would you be able to write up the pull request for this?  If not, I can do it

**Comment by Gabriel439** [comment]
Fixed by #30 

I can upload this to Hackage if you don't have any other pending changes you'd like to submit

**Comment by Gabriel439** [comment]
I had to revert this change due to #32

**Comment by jkarni** [comment]
Fair enough - thanks for letting me know!

**Comment by treeowl** [comment]
Should this be reopened? It seems the underlying problem has been fixed in GHC, according to comments in #32.

**Comment by Gabriel439** [comment]
My only question is whether or not this requires a major version bump or not if we reintroduce this.  I'm reviving the discussion in that issue

**Comment by Gabriel439** [comment]
Alright, so the plan is to reintroduce this change but with a major version bump so that downstream libraries that might be affected by the GHC bug (and/or kind inference ambiguity) aren't affected.
